<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Excluir MainWallE.cs del build -->
    <!--<Compile Remove="MainWallE.cs" /> -->
    <!-- Evita compilar archivos de código .cs -->
    <Compile Remove="PixelWallE.GUI/**/*.cs" />
    <!-- Evita incluir archivos que no se compilan (axaml, txt, etc.) -->
    <None Remove="PixelWallE.GUI/**/*.*" />
    <Content Remove="PixelWallE.GUI/**/*.*" />
    <EmbeddedResource Remove="PixelWallE.GUI/**/*.*" />
  </ItemGroup>

</Project>
